"use client";

import { Button, ConfigProvider, Table, theme, Typography } from "antd";
import type { ColumnsType } from "antd/es/table";
import { useCallback, useRef, useState } from "react";
import { useReactToPrint } from "react-to-print";

const { Title } = Typography;

interface TableClientPageProps<T> {
  title: string;
  columns: ColumnsType<T> | undefined;
  generateData: () => T[];
  initialData?: T[];
}

export function TableClientPage<T extends { key: string }>({
  title,
  columns,
  generateData,
  initialData,
}: TableClientPageProps<T>) {
  const [data, setData] = useState<T[]>(initialData ?? generateData());
  const componentRef = useRef<HTMLDivElement>(null);

  const handleRefresh = useCallback(() => {
    setData(generateData());
  }, [generateData]);

  const handlePrint = useReactToPrint({
    contentRef: componentRef,
    pageStyle: `
      @page {
        size: A4;
        padding: 16px;
        margin: 0;
      }
    `,
  });

  return (
    <div className="py-6">
      {/* 标题和操作按钮 */}
      <div className="mb-6 flex items-center justify-between">
        <Title level={1}>{title}</Title>
        <div className="space-x-4">
          <Button onClick={handleRefresh} type="primary">
            Generate New Data
          </Button>
          <Button onClick={() => handlePrint()}>Print Table</Button>
        </div>
      </div>

      {/* 表格区域 */}
      <div ref={componentRef}>
        <ConfigProvider theme={{ algorithm: theme.compactAlgorithm }}>
          <Table
            columns={columns}
            dataSource={data}
            pagination={false}
            bordered
            footer={() => (
              <div className="flex justify-between text-gray-500">
                <span>Generated by RandomKits</span>
                <span>randomkits.com</span>
              </div>
            )}
          />
        </ConfigProvider>
      </div>
    </div>
  );
}
